### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by skoften** [matt-west/craft-recaptcha#1]
![screen shot 2018-05-24 at 10 47 38](https://user-images.githubusercontent.com/1286410/40474653-e6924720-5f3f-11e8-9a58-232aca7f232e.jpg)

**Comment by matt-west** [comment]
Hey @skoften! Do you have the [Craft contact-form](https://github.com/craftcms/contact-form) plugin installed?

**Comment by skoften** [comment]
Hi Matt,

Nope, currently I am using Wheel Form plugin for this type of forms: https://github.com/xpertbot/craft-wheelform

**Comment by matt-west** [comment]
Hey @skoften, this is is now fixed in [v1.0.1](https://github.com/matt-west/craft-recaptcha/releases/tag/v1.0.1).
