### ISSUE TITLE
Contact Form passes through without recaptcha checked

### ISSUE THREAD

**Issue by AmirNaghibi** [matt-west/craft-recaptcha#10]
I have added `{{craft.recaptcha.render()}}` to the form tag inside my contact.html form. When clicking the submit button **with EMPTY recaptcha**, the form goes through successfully. 

I wasn't sure where to put the **Verify the reCAPTCHA** script so I just put it inside <script> tag on top of html. 

Here are my questions: 
1. how can i make sure that the form does not go through unless the recaptcha is checked? 
2. Is the **Verify the reCAPTCHA** necessary? or can I just get the desired functionality with  `{{craft.recaptcha.render()}}` tag. 

Thanks in advance for your help! :)

**Comment by AmirNaghibi** [comment]
Also for the following line in Validating the reCAPTCHA: 
`$captcha = Craft::$app->getRequest()->getParam('g-recaptcha-response');`
I get the error: 
`Fatal error: Uncaught Error: Class 'Craft' not found`

**Comment by matt-west** [comment]
Hi @AmirNaghibi,

Are you using the [Craft Contact Form plugin](https://github.com/craftcms/contact-form) or have you implemented your own contact form handler?

**Comment by AmirNaghibi** [comment]
No, it's just a regular HTML form.
{{craft.recaptcha.render()}} brings a reCaptcha icon to the page, but I'm having difficulty validating it to make sure the recaptcha box has been checked.

**Comment by matt-west** [comment]
@AmirNaghibi You’ll need to [manually verify the recaptcha](https://github.com/matt-west/craft-recaptcha#verify-the-recaptcha) in your code that handles form submissions.
