### ISSUE TITLE
How to disable the recaptcha check on ajax forms

### ISSUE THREAD

**Issue by sunscreem** [matt-west/craft-recaptcha#13]
Got this running perfectly on the standard craft contact form and plug in.

I've a different form I'm submitting via post request (generated via axois). Its failing because, obviously, its looking for the recaptcha fields.

Is there a way to say to this plug in "don't try and validate for XXX form?"

**Comment by matt-west** [comment]
I’d recommend disabling the default contact form validation in the config and then writing a custom validation hook that checks which form is being processed before validating the recaptcha.

You can disable the contact form validation in the [plugin config](https://github.com/matt-west/craft-recaptcha/blob/master/src/config.php):

```php
return [
   "siteKey" => "...",
    "secretKey" => "...",
    "validateContactForm" => false
];
```

[Here are some instructions](https://github.com/matt-west/craft-recaptcha#verify-the-recaptcha) on how to manually validate the recaptcha. You’ll need to [create a new plugin](https://pluginfactory.io) and then place this code in the `init()` function.
