### ISSUE TITLE
No error handling when craft-recaptcha is active

### ISSUE THREAD

**Issue by bm-jeroendewilde** [matt-west/craft-recaptcha#15]
When the craft-recaptcha plugin is active, no errors are display on the fields used in the contact form.

The captcha itself is rendered by:
`{{ craft.recaptcha.render() }}`

The errors for the fields used in the contact form are rended by:
`{{ message is defined and message ? errorList(message.getErrors('message.body')) }}`

Only when the "I'm not a robot" in the Recaptcha box is checked, errors are displayed.

### Expectation

- Show an error when the recaptcha box is not checked.
- Show errors when fields used in the contact form are not valid, even when the recaptcha box is not checked.

**Comment by dmatthams** [comment]
Did you get anywhere with this? I have the same issue.

**Comment by dmatthams** [comment]
You need to retrieve error with: {{  message is defined and message ? errorList(message.getErrors('recaptcha')) }}
