### ISSUE TITLE
recaptcha script tag not rendered when ajax request

### ISSUE THREAD

**Issue by timkelty** [matt-west/craft-recaptcha#16]
Apparently in Craft 3, the registered js files don't get dumped if the response is an HTML fragment (ie it doesn't have html/body tags). In craft 2 it would still dump those scripts at the bottom of the template.

To do this with this plugin, you can do something like this in your ajax template:

```
{{ view.getBodyHtml()|raw }}
```

**Comment by timkelty** [comment]
https://github.com/craftcms/cms/issues/5705

**Comment by matt-west** [comment]
Thanks for the heads up @timkelty. Can you please add a note about this to the README and submit your changes in a PR.
