### ISSUE TITLE
Badge not showing for Invisible reCaptcha

### ISSUE THREAD

**Issue by diegovogel** [matt-west/craft-recaptcha#17]
I'm using invisible reCaptcha with the Craft CMS Contact Form plugin. As far as I can tell it's working ok, but I can't get the badge to show up. I tried the automatic integration as well as adding this to the form markup (right before the submit button):
```
<div class="g-recaptcha"
  data-sitekey="{{ craft.recaptcha.sitekey }}"
  data-callback="onSubmit"
  data-size="invisible"
  data-badge="bottomright">
</div>
```

Any idea what to try next? Thanks.

**Comment by matt-west** [comment]
Hey @diegovogel!

Have you tried this?

```
{{ craft.recaptcha.render({
  callback: 'onSubmit',
  size: 'invisible',
  badge: 'bottomright'
}) }}
```

Perhaps check the Craft log to make sure the recaptcha token is being submitted with the form.

**Comment by diegovogel** [comment]
That worked! Thanks a lot Matt.

**Comment by matt-west** [comment]
Awesome! Glad you’re all sorted. :)
