### ISSUE TITLE
Recaptcha verification

### ISSUE THREAD

**Issue by Herokid** [matt-west/craft-recaptcha#2]
Hi,
If I use contact-form, ¿I need 'Verify the reCAPTCHA'?

Thanks!

**Comment by matt-west** [comment]
You’ll need to add the following tag to your contact form twig template to display the reCAPTCHA widget.

```twig
{{ craft.recaptcha.render() }}
```

**Comment by Herokid** [comment]
Ok, thanks!
I ask this because when i click on 'I'm not a robot', the spinner never ends.

The problem must be another.

Have a nice day @matt-west (:

**Comment by matt-west** [comment]
That’s odd. Let me know if you find a solution so we can post the answer for anyone else that encounters the same issue.

**Comment by Herokid** [comment]
Hi @matt-west 
yes, i know what is the problem.

Is really strange, maybe is a Chrome bug.
If I have devtools open, the spinner is allways running. If i have devtools close, all works correctly.

I have the same issue with disqus plugin. Both plugin only fail when devtool is open.

If you need a video demo just tell me.

Have a nice day!

**Comment by matt-west** [comment]
Thanks for letting me know. :)
