### ISSUE TITLE
no any error message

### ISSUE THREAD

**Issue by Bronskiy** [matt-west/craft-recaptcha#22]
Hi, how can I show an error message if user didn't verify captcha?

**Comment by Bronskiy** [comment]
Found a solution:
```
    {% set messages = craft.app.session.getAllFlashes() %}
    {% if messages|length > 0 %}
        {% for message in messages %}
             {{ message }}<br>
        {% endfor %}
    {% endif %}
```
Is it better to use some error message variable? Like `Craft::$app->session->setFlash('yourVariable', "Something happened yo!");`
I can make pull request if it is easier.

**Comment by matt-west** [comment]
Hi @Bronskiy,

Are you using the Craft contact form plugin?

You should be able to pull the error from the message object.

```
{% if message is defined and message.getErrors('recaptcha')|length > 0 %}
  <div class="form-error">
    <p>Sorry, we couldn’t verify that you are human. Please try again!</p>
  </div>
{% endif %}
```

**Comment by parwinderD4D** [comment]
Hi, I'm using Recaptcha while registering users on Craft Site,  I have used @Bronskiy above-mentioned code and it shows me the default error message **Unable to verify your submission.**  By I want to replace this message with **We couldn’t verify that you are human. Please try again!**

Could you please guide me on it?
Looking Forward.
