### ISSUE TITLE
Validation within twig template

### ISSUE THREAD

**Issue by cap-akimrey** [matt-west/craft-recaptcha#26]
I have a custom form (so no Craft Contact Form) with the action to send to an external URL (Salesforce Web to Case). The reCaptcha widget displays fine with 
`{{ craft.recaptcha.render() }}`

but implementation of the validation function:
`// Get the reCAPTCHA response code to validate.
        $captcha = Craft::$app->getRequest()->getParam('g-recaptcha-response');

        // Pass the response code to the verification service.
        $validates = CraftRecaptcha::$plugin->craftRecaptchaService->verify($captcha);

        if ($validates) {
        // All good! the reCAPTCHA is valid.
        } else {
        // The reCAPTCHA is invalid.
        }`

is unclear, and the form sends regardless of user interaction with the widget.

**Comment by matt-west** [comment]
Hi @cap-akimrey!

Can you please share the form markup from your twig template.

**Comment by cap-akimrey** [comment]
Thanks, @matt-west, I've been on vacation. Please see attached.
[index.twig.zip](https://github.com/matt-west/craft-recaptcha/files/6918610/index.twig.zip)

**Comment by matt-west** [comment]
Hey @cap-akimrey,

It's not possible to validate the reCAPTCHA from the Twig template. (Lines 323-333 in your code)
You'll need to build a plugin that receives the form submission, validates the reCAPTCHA, then forwards the submission on to Salesforce if the reCAPTCHA is good.
