### ISSUE TITLE
How to change re-captcha language based on current site language ?

### ISSUE THREAD

**Issue by parwinderD4D** [matt-west/craft-recaptcha#27]
Hi, could you please let me know how we can change Recaptcha language based on the website's current language?

For example: if a user opens a website in the French language then it will show Captcha text in French and the same for other languages, Please have a look at the screen-shot :  
![image](https://user-images.githubusercontent.com/46927214/132873475-dac47cc0-fc6e-4444-bdcc-8141ff5b68da.png)

As I have done some RnD and found that we have to pass language code into javascript file as mentioned below in code. 
`<script src='https://www.google.com/recaptcha/api.js?hl=fr'></script>`
and if follow the same thing so in the plugin core file I have added the `?hl=fr` and it works fine. 

could you please guide me on how I can make it work without doing changes in the core file? 

Looking Forward.
Parwinder

**Comment by matt-west** [comment]
Hey Parwinder,

It's not possible to do this with the current plugin. You could create a fork of this repo and update this line to achieve it though: https://github.com/matt-west/craft-recaptcha/blob/24f315630c9c12f6d2d4f26e5382cfced396f4ae/src/services/CraftRecaptchaService.php#L42
