### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by jnaklaas** [matt-west/craft-recaptcha#29]
Hi, I've added the plugin manually to an existing project. Installed with composer locally, then uploaded the plugin with ftp, same for the craftcms/plugins.php file. I installed and configured the plugin, and try to use it with the official craft form plugin.

With the plugin active and *Enable to automatically validate reCAPTCHAs when using the official Craft CMS contact form plugin.*
enabled, it shows an internal server error page after submitting forms.

This is a related part of the craft log of the failing post requests:
```
$_POST = [
    'CRAFT_CSRF_TOKEN' => '•••••••'
    'action' => 'contact-form/send'
    'redirect' => 'b3c09816c20395ae7fce033801aaaf66a3917d9a37231ebb615bc7c5e8426d64url
    'subject' => 'subject'
    'fromName' => 'jnaklaas'
    'message' => [
        'body' => 'TEST'
    ]
    'fromEmail' => 'name@email.com'
]

$_SESSION = [
    'bd62416aa8538ede709019a5e113eea5__flash' => [
        'error' => 1
    ]
    '1031b8c41dfff97a311a7ac99863bdc5__id' => '1'
    '1031b8c41dfff97a311a7ac99863bdc5__expire' => 1639052986
    'error' => 'There was a problem with your submission, please check the form and try again!'
]
```

When disabling the auto validation, the form works properly.

The web inspector shows no requests to google's recaptcha.js file - I'm not sure if this is expected behaviour.  Adding code below does load the recaptcha.js. But it still doesn't show a badge - and still shows the internal server error page on submit.

```
{{ craft.recaptcha.render({
  callback: 'onSubmit',
  size: 'invisible',
  badge: 'bottomright'
}) }}
```

craft cms version: 3.0.32
contact-form version: 2.2.2
craft-recaptcha version: 1.2.0

**Comment by matt-west** [comment]
Hi @jnaklaas,

Does it work if you use the regular reCAPTCHA rather than the invisible version?

You need to do some extra work to make the invisible reCAPTCHA work. See the documentation here for how you should catch the form submission using JavaScript and execute the reCAPTCHA:
https://developers.google.com/recaptcha/docs/invisible

You can still access the key stored by the plugin, but you’ll probably need to add the markup manually rather than using the template helper. For example:

```
<div class="g-recaptcha"
      data-sitekey="{{ craft.recaptcha.sitekey }}"
      data-callback="onSubmit"
      data-size="invisible">
</div>
```
