### ISSUE TITLE
Add forced test key + secret for local testing

### ISSUE THREAD

**Issue by rswhite7** [matt-west/craft-recaptcha#3]
[Google's docs say](https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha-v2-what-should-i-do) that if you add this test key and secret, you can test locally and get a success every time:

- Site key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
- Secret key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe

It would be cool if the plugin automatically did this if it was being used in the local environment.

**Comment by matt-west** [comment]
Thanks for the suggestion @rswhite7. 

I’d prefer not to make this automatic as some people may want to be able to test reCAPTCHA failures locally. I’ve added a note about these credentials to the [README](https://github.com/matt-west/craft-recaptcha/blob/master/README.md) instead.

**Comment by rswhite7** [comment]
@matt-west true, but consider maybe as a future feature a switch in the CP that would override the key and secret with Google's test ones.  The reason I bring this up is that if you are using something like nystudio107's [database syncing](https://nystudio107.com/blog/database-asset-syncing-between-environments-in-craft-cms) from a remote environment, these settings constantly get overwritten in the local environment.  Having something like a config file or a CP switch to turn on and off for local testing could be really helpful.  Otherwise, it's just a lot of manual copying and pasting.
