### ISSUE TITLE
Site isn't verifying reCAPTCHA solutions

### ISSUE THREAD

**Issue by paul-frost** [matt-west/craft-recaptcha#36]
In the Google reCAPTCHA control panel in the last few days I've started getting a warning message:
"We detected that your site isn't verifying reCAPTCHA solutions. This is required for the proper use of reCAPTCHA on your site. Please see [our developer site](https://developers.google.com/recaptcha/docs/verify#api-request) for more information."

In the Firefox developer tools Console I get multiple:
"Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified"
"Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified"
"Partitioned cookie or storage access was provided to “https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LfxOHohAAAAACE2XgP5V9K9PDJfFXfkDMOd_xoR&co=aHR0cHM6Ly93d3cuZGZvay5jby51azo0NDM.&hl=en-GB&v=g8G8cw32bNQPGUVoDvt680GA&size=normal&cb=mjvhmicq3dqd” because it is loaded in the third-party context and dynamic state partitioning is enabled."

But the graph showing requests passed and failed still reports numbers for recent days and the form is still showing the reCAPTCHA and sending on emails.

**Comment by matt-west** [comment]
Hey @paul-frost, what happens if you try to submit your form without completing the reCAPTCHA?

**Comment by paul-frost** [comment]
I get an error message of "Please verify you are human." and the form doesn't get submitted.
You can see the form in action here https://www.dfok.co.uk/contact/paul-frost

**Comment by honsa** [comment]
I could fullfill the form with and it worked

![image](https://user-images.githubusercontent.com/526006/189488087-aabe398b-7806-41f8-a82f-267541bda8f7.png)

**Comment by paul-frost** [comment]
But I'm still getting the warning on the reCAPTCHA control panel, see attached screenshot.
![Screenshot 2022-09-10 at 15 38 10](https://user-images.githubusercontent.com/384378/189488304-116130f4-1f90-460a-b55e-3205d6b10164.png)

**Comment by honsa** [comment]
Seems ok to me, 1 verified, that was me. 

If you continue with this setup, the stats should show more verified.

**Comment by paul-frost** [comment]
Thanks for investigating this. The warning message has gone this morning, maybe due to there being 4 uses yesterday.
Apologies, as it seems as if this was not a bug in the plugin but poor reporting from Google.

Unfortunatly it's not completly blocking the spammers though. But I guess if a real person is sending the message there isn't much to prevent those.

**Comment by honsa** [comment]
You can try it with a hidden input, if its filled than the chances are big thats just a bot. Honey for the robots ;)

**Comment by paul-frost** [comment]
Thanks honsa, I am already using the HoneyPot plugin as well.
