### ISSUE TITLE
Is this plugin support google recaptcha v3?

### ISSUE THREAD

**Issue by xiaoxin01** [matt-west/craft-recaptcha#5]
Hi,

Is this plugin support google recaptcha v3?

Some people think that google recaptcha v2 is too difficult to use:

    https://productforums.google.com/forum/#!topic/websearch/tFHDAsX4Ypk

I think v3 is better to use:

    https://developers.google.com/recaptcha/docs/v3

Thanks:)

**Comment by matt-west** [comment]
No. It currently uses v2.

**Comment by DAgcy** [comment]
> No. It currently uses v2.
Hey!
What about v3 support? Will it be available soon?

**Comment by DAgcy** [comment]
> No. It currently uses v2.

Hey!
What about v3 support? Will it be available soon?

**Comment by matt-west** [comment]
Hey @DAgcy,

I have no plans to add support for v3 at the moment.

**Comment by matt-adigital** [comment]
Can this please be added to the documentation that v3 is not supported. Just spent some time trying to figure out if it's a recaptcha error only to find this issue. Thank you.

**Comment by matt-west** [comment]
@matt-adigital Absolutely. I’ve added that to the README. I’ll try and find time to add support for v3 in the next couple weeks.

**Comment by matt-adigital** [comment]
Thank you very much, great plugin by the way!
